// Phase 4 — keep the planning simulation honest against the shopping side.
//
// The grocery list is generated by the existing flow (GenerateGrocerySheet),
// whose consolidation and pantry subtraction are the same steps the Phase 1
// engine performs: consolidate the whole plan per identity key and unit bucket,
// then subtract pantry with safe unit conversion only. So the engine is used as
// the shared reference for what "still needed" means.
//
// This module only COMPARES. It never produces a second shopping calculation —
// where the two disagree the difference is surfaced as a caveat for the user.

import { evaluatePlanCost, type PlanMeal, type PantrySnapshotItem } from "@/lib/cost/engine";
import { convertQuantity } from "@/lib/grocery";
import type { SimulationResult, SimMeal, SimPantryItem } from "./inventory";
import type { PriceResolver } from "@/lib/cost/resolver";

export type ReconcileDifference = {
  name: string;
  /** What the planning simulation says still has to be bought. */
  simulated: string;
  /** What the shared grocery/cost reference says. */
  reference: string;
  reason: "quantity" | "missing_line" | "extra_line";
};

const fmt = (q: number | null, u: string | null) =>
  q == null ? "unknown amount" : `${Math.round(q * 100) / 100}${u ? ` ${u}` : ""}`;

/**
 * Compare the simulation's pre-pack missing requirements with the shared
 * reference for the same meals and pantry. Differences are only reported when
 * the two figures are genuinely comparable (same identity, convertible units).
 */
export const reconcileWithGrocery = (
  sim: SimulationResult,
  meals: SimMeal[],
  pantry: SimPantryItem[],
  opts: { currency: string; resolver: PriceResolver; tolerance?: number },
): ReconcileDifference[] => {
  const tolerance = opts.tolerance ?? 0.02; // 2 %
  const reference = evaluatePlanCost(
    meals.map<PlanMeal>((m) => ({
      id: m.slotId,
      date: m.date,
      mealType: m.mealType,
      title: m.title,
      servings: m.servings,
      recipeServings: m.recipeServings,
      ingredients: m.ingredients,
    })),
    pantry.map<PantrySnapshotItem>((p) => ({
      name: p.name,
      quantity: p.quantity,
      unit: (p.unit as PantrySnapshotItem["unit"]) ?? null,
      expiresOn: p.expiresOn ?? null,
    })),
    { currency: opts.currency, resolver: opts.resolver },
  );

  const out: ReconcileDifference[] = [];
  const refLines = reference.lines.filter((l) => (l.missingQuantity ?? 0) > 0);
  const seen = new Set<string>();

  for (const line of refLines) {
    const match = sim.missing.find((m) => m.identityKey === line.identityKey);
    if (!match) {
      out.push({
        name: line.name,
        simulated: "nothing needed",
        reference: fmt(line.missingQuantity, line.requiredUnit),
        reason: "missing_line",
      });
      continue;
    }
    seen.add(match.identityKey);
    const simInRefUnit = convertQuantity(match.quantity, match.unit, line.requiredUnit);
    if (simInRefUnit == null) continue; // not comparable — no claim made
    const refQty = line.missingQuantity ?? 0;
    const denom = Math.max(refQty, simInRefUnit, 0.0001);
    if (Math.abs(simInRefUnit - refQty) / denom > tolerance) {
      out.push({
        name: line.name,
        simulated: fmt(match.quantity, match.unit),
        reference: fmt(refQty, line.requiredUnit),
        reason: "quantity",
      });
    }
  }

  for (const m of sim.missing) {
    if (seen.has(m.identityKey)) continue;
    if (refLines.some((l) => l.identityKey === m.identityKey)) continue;
    out.push({
      name: m.name,
      simulated: fmt(m.quantity, m.unit),
      reference: "nothing needed",
      reason: "extra_line",
    });
  }

  return out;
};
