// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get_app_info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_app_info_default = defineTool({
  name: "get_app_info",
  title: "Get app info",
  description: "Return a high-level description of Fuudit \u2014 what it is, who it's for, and where to try it.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          "Fuudit \u2014 your playful and smart kitchen assistant.",
          "Tagline: From pantry to plate \u2014 no waste, just taste.",
          "",
          "Fuudit helps home cooks reduce food waste, plan meals, track their pantry, and get AI-powered recipe inspiration based on what they already have at home. A B2B offering (Fuudit for Businesses) covers restaurants & catering, grocery retail, corporate wellbeing, smart tech partners, and hospitality / multi-location chains.",
          "",
          "Discover the MVP: https://www.fuudit.com",
          "Waiting list / signup: https://signup.fuudit.com"
        ].join("\n")
      }
    ],
    structuredContent: {
      name: "Fuudit",
      tagline: "From pantry to plate \u2014 no waste, just taste.",
      mvpUrl: "https://www.fuudit.com",
      signupUrl: "https://signup.fuudit.com",
      businessContact: "hello@fuudit.com"
    }
  })
});

// src/lib/mcp/tools/list_features.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var FEATURES = [
  { title: "Smart Ingredient Search", description: "Enter ingredients you have at home and get real-time recipe suggestions from an extensive database." },
  { title: "AI Chef Assistant", description: "Personalized recipes based on your ingredients, dietary goals, and cooking style preferences." },
  { title: "Leftover Remix", description: "Transform yesterday's meals into today's inspiration with creative leftover recipe suggestions." },
  { title: "Meal Planning", description: "Plan your week with a smart calendar and never run out of meal ideas." },
  { title: "Smart Grocery Companion", description: "Auto-generates shopping lists from your pantry and meal plan, and recommends what to buy next based on health goals, habits, and upcoming needs." },
  { title: "Pantry Tracking", description: "Track expiration dates and get alerts to use ingredients before they go bad." }
];
var COMING_SOON = [
  { title: "Personalized Nutrition Engine", description: "Integrate your genetic test or nutrition profile so Fuudit personalizes ingredient and meal suggestions to your body." },
  { title: "Bio-Aware Food Suggestions", description: "Adapts to your sleep, cycle, stress, and movement data from wearables (Oura, RingConn, Apple Watch) to suggest real-time supportive meals." }
];
var list_features_default = defineTool2({
  name: "list_features",
  title: "List Fuudit features",
  description: "List Fuudit's current consumer features and upcoming (coming-soon) features.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          "Available today:",
          ...FEATURES.map((f) => `- ${f.title}: ${f.description}`),
          "",
          "Coming soon:",
          ...COMING_SOON.map((f) => `- ${f.title}: ${f.description}`)
        ].join("\n")
      }
    ],
    structuredContent: { available: FEATURES, comingSoon: COMING_SOON }
  })
});

// src/lib/mcp/tools/list_business_offerings.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var OFFERINGS = [
  {
    segment: "Restaurants & Catering",
    pitch: "Cut food waste and boost margins with AI-powered menu & stock optimization.",
    features: [
      "Real-time AI-powered inventory & waste tracking",
      "Menu optimization based on available stock",
      "Dynamic pricing suggestions to move soon-to-expire stock",
      "Staff-facing AI assistant for recipe and portion adjustments"
    ]
  },
  {
    segment: "Grocery Retail",
    pitch: "Engage customers with smart expiry alerts, recipe tie-ins, and sustainable stock flow.",
    features: [
      "Smart expiry alerts to move short-dated stock",
      "Recipe tie-ins that turn inventory into inspiration",
      "Sustainable stock flow guidance"
    ]
  },
  {
    segment: "Corporate Wellbeing",
    pitch: "Bring smarter, healthier, waste-free food to your workplace.",
    features: [
      "Personalized meal recommendations for employees",
      "Waste-aware canteen and catering planning",
      "Wellbeing-focused nutrition programs"
    ]
  },
  {
    segment: "Smart Tech Partners",
    pitch: "Turn every kitchen device into a food-waste-fighting assistant.",
    features: [
      "API/SDK for smart fridges, ovens, and kitchen appliances",
      "Recipe & inventory intelligence for connected devices"
    ]
  },
  {
    segment: "Hospitality & Multi-Location Chains",
    pitch: "Optimize food operations across all outlets with centralized AI-driven insights.",
    features: [
      "Unified inventory dashboards across all locations",
      "Predictive ordering to reduce overstocking",
      "Insights on usage patterns, costs, and waste reduction ROI"
    ]
  }
];
var list_business_offerings_default = defineTool3({
  name: "list_business_offerings",
  title: "List Fuudit for Businesses offerings",
  description: "List Fuudit's B2B segments (restaurants, retail, corporate wellbeing, smart tech, hospitality chains) with their pitches and feature highlights.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: OFFERINGS.map(
          (o) => `## ${o.segment}
${o.pitch}
${o.features.map((f) => `- ${f}`).join("\n")}`
        ).join("\n\n") + "\n\nContact: hello@fuudit.com"
      }
    ],
    structuredContent: { offerings: OFFERINGS, contactEmail: "hello@fuudit.com" }
  })
});

// src/lib/mcp/tools/articles.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var ARTICLES = [
  {
    slug: "future-of-food-waste-smart-tech",
    title: "The Future of Food Waste: How Smart Tech is Redefining How We Eat",
    author: "Ebe Meitern-Vare",
    date: "2025-11-05",
    excerpt: "Nearly one-third of food produced globally is wasted. Discover how AI and smart tech \u2014 including Fuudit \u2014 are turning that around.",
    url: "https://fuudit.lovable.app/articles/future-of-food-waste-smart-tech",
    content: `Nearly one-third of all food produced globally never gets eaten. Behind that statistic lies more than waste \u2014 it represents lost energy, water, time, and opportunity. Food waste is not only a household inconvenience; it's a social, environmental, and economic challenge that affects every corner of the planet.

But the good news is that change is already happening. It's powered by technology, design, and the collective willingness to make small yet meaningful shifts in how we live and eat.

At Fuudit, we believe that sustainability should feel simple \u2014 not like an extra task on your to-do list. Our AI-driven food waste companion helps people track what they have at home, use ingredients smartly, and rediscover the joy of cooking sustainably.

## From Awareness to Intelligent Action

Recent years have brought a wave of innovation in food technology \u2014 Too Good To Go, OLIO, Lifesum, and others. Most tools address only one part of the problem: redistribution, calorie tracking, or meal inspiration. Fuudit takes a full-circle approach \u2014 expiration tracking, AI-based recipe suggestions, leftover remixing, and smart shopping reminders \u2014 in one intuitive Scandinavian-inspired interface.

## Insights from the Fuudit Community

Users want to reduce food waste but struggle with planning, overbuying, and knowing what to cook next. Vegetables and chicken are the most-wasted ingredients. The top motivators for change are cooking inspiration, better use of leftovers, picture recognition / fridge scanning, smart meal planning, and time savings.

## The Next Wave of Food Tech

Pantries will sync with grocery platforms for predictive shopping. Smart fridges will notify users about expiring items. Wearables (Oura, RingConn, Apple Watch) will personalize meal suggestions by mood, sleep, or hormonal balance. Fuudit's modular AI-powered architecture is designed to integrate with smart appliances, health data, and retailers.

## A Simpler, More Sustainable Future

Food waste is about how we plan, connect with food, and let technology make mindful living effortless. Fuudit helps people cook smarter, waste less, and enjoy food again \u2014 one meal at a time.

Explore Fuudit at https://www.fuudit.com \u2014 sign up for early access at https://signup.fuudit.com.`
  }
];
var listArticlesTool = defineTool4({
  name: "list_articles",
  title: "List Fuudit articles",
  description: "List all published Fuudit articles with title, author, publish date, excerpt, and slug.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = ARTICLES.map(({ content, ...meta }) => meta);
    return {
      content: [
        {
          type: "text",
          text: items.map((a) => `- ${a.title} (${a.date}) by ${a.author}
  slug: ${a.slug}
  ${a.excerpt}`).join("\n\n")
        }
      ],
      structuredContent: { articles: items }
    };
  }
});
var getArticleTool = defineTool4({
  name: "get_article",
  title: "Get Fuudit article",
  description: "Fetch the full text of a Fuudit article by its slug. Use `list_articles` first to discover valid slugs.",
  inputSchema: {
    slug: z.string().min(1).describe("Article slug, e.g. 'future-of-food-waste-smart-tech'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const article = ARTICLES.find((a) => a.slug === slug);
    if (!article) {
      return {
        content: [{ type: "text", text: `No article found with slug "${slug}". Call list_articles for available slugs.` }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `# ${article.title}
_${article.author} \u2014 ${article.date}_

${article.content}`
        }
      ],
      structuredContent: { article }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "fuudit-mcp",
  title: "Fuudit",
  version: "0.1.0",
  instructions: "Public MCP server for Fuudit \u2014 a playful, AI-powered kitchen assistant that helps people reduce food waste, plan meals, and get recipes from what's in their pantry. Use these tools to answer questions about Fuudit's product, its B2B offerings, and its published articles.",
  tools: [get_app_info_default, list_features_default, list_business_offerings_default, listArticlesTool, getArticleTool]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
